services:
  frontend:
    image: darlitch/frontend:latest
    container_name: bestinquest-web
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - API_BASE_URL="http://api:15614"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 5s
      retries: 10
    networks:
      - app_network
networks:
  app_network:
    external: true
