export const tasks = [
  {
    title: 'Почистить зубы',
    startTime: '9:00',
    duration: '30 мин',
    projectName: 'Проект A',
    author: 'Вася Пупкин',
    sphere: 'Привычки',
    status: true,
    priority: false,
  },
  {
    title: 'Сделать домашку',
    startTime: '10:00',
    duration: '45 мин',
    projectName: 'Проект B',
    author: 'Петров П.П.',
    sphere: 'Школа',
    status: false,
    priority: false,
  },
  {
    title: 'Помыть посуду',
    startTime: '11:00',
    duration: '30 мин',
    projectName: 'Проект A',
    author: 'Иванов И.И.',
    sphere: 'Домашние дела',
    status: true,
    priority: true,
  },
  {
    title: 'Спорт зал',
    startTime: '20:00',
    duration: '60 мин',
    projectName: 'Проект A',
    author: 'Вася Пупкин',
    sphere: 'Спорт',
    status: false,
    priority: true,
  },
]