export const tasks = [
  {
    title: 'Почистить зубы',
    startTime: '9:00',
    duration: '30 мин',
    projectName: 'Проект A',
    assignee: 'Я',
    sphere: 'Финансы',
    isCompleted: true,
    isImportant: false,
  },
  {
    title: 'Сделать домашку',
    startTime: '10:00',
    duration: '45 мин',
    projectName: 'Проект B',
    assignee: 'Петров П.П.',
    sphere: 'Маркетинг',
    isCompleted: false,
    isImportant: false,
  },
  {
    title: 'Помыть посуду',
    startTime: '11:00',
    duration: '30 мин',
    projectName: 'Проект A',
    assignee: 'Иванов И.И.',
    sphere: 'Финансы',
    isCompleted: true,
    isImportant: true,
  },
  {
    title: 'Спорт зал',
    startTime: '20:00',
    duration: '60 мин',
    projectName: 'Проект A',
    assignee: 'Я',
    sphere: 'Финансы',
    isCompleted: false,
    isImportant: true,
  },
]